# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# 输出URL样式 /2009/04/06/zh/index.html
Permalinks:      		pertty
relative_permalinks:    true

# Setup
title:  				前端手艺人
tagline: 				'一个前端菜鸟的自嘲'
description:  			'关于我 <a href="http://github.com/wohaiwo" target="_blank">我</a>'
# 链接 site.baseurl 固定链接  post.url 内部链接
url:                  	http://wohaiwo.github.io
baseurl:              	''
# 分页设置信息
# 每页文章数量
paginate:            	4		
paginate_path:  	 

# About/contact
author:
  name:              
  url:               
  email: 			zhome621@gmail.com
github:  			https://github.com/wohaiwo

#分页插件



