# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               前端手艺人
tagline:             '一个前端菜鸟的自嘲'
description:         '关于我 <a href="https://github.com/wohaiwo" target="_blank">我</a>'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:             
  url:               https://wohaiwo.github.io
  email:             zhome621@gmail.com


